baseURL = "http://wanjiabing.top/"
languageCode = "zh-CN"
DefaultContentLanguage = "zh" 
theme = "anatole"
readMore = true

[params]
title = "冰冰的小屋"
author = "万家兵"
description = "自由 | 快乐"
profilePicture = "image/head.jpg"
copyright = "2020-2024 鲁ICP备20020558号-1"

singleDateFormat = "2006-01-02 Mon"
indexDateFormat = "2006-01-02 Mon"
listDateFormat = "01-02"
readMore = true

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

[Languages]
  [Languages.zh]
   weight = 1
   LanguageName = "中文"
   title = "冰冰的小屋"
   author = "万家兵"
   description = "自由 | 快乐"
   profilePicture = "image/head.jpg"
   readMore = true
   copyright = "2020-2023 鲁ICP备20020558号-1"

   [[Languages.zh.menu.main]]
    name = "主页"
    identifier = "home"
    weight = 100
    url = "/"

    [[Languages.zh.menu.main]]
    name = "博客"
    weight = 200
    identifier = "posts"
    url = "/posts/"

    [[Languages.zh.menu.main]]
    name = "关于"
    weight = 300
    identifier = "about"
    url = "/about/"

   [Languages.en]
   weight = 2
   LanguageName = "EN"
   title = "I'm Jiabing Wan."
   author = "Jiabing Wan"
   readMore = true
   description = "Freedom and happiness"
   profilePicture = "image/head.jpg"

   [[Languages.en.menu.main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/en/"

    [[Languages.en.menu.main]]
    name = "Posts"
    weight = 200
    identifier = "posts"
    url = "/en/posts/"

    [[Languages.en.menu.main]]
    name = "About"
    weight = 300
    identifier = "about"
    url = "/en/about/"
 
   

